environment: stage

deployment:
  image:
    tag: 0
  replicas: 1
  env:
    redis_host: davey-stage-elascache-rep-group.o3ypfk.ng.0001.euw2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline